debug code removed, remove open path aware
path splitting code was repeated 3 times, now one method does this job.
special cases with open something/..; open something/., solved.
read of the folder prohibited
isnuber returns sector number(before it was returning 1 if it was the file)

SUMMARY BY TEST SET

Test Set                                      Pts Max  % Ttl  % Max
--------------------------------------------- --- --- ------ ------
tests/filesys/extended/Rubric.functionality    29/ 34  25.6%/ 30.0%
tests/filesys/extended/Rubric.robustness        7/ 10  10.5%/ 15.0%
tests/filesys/extended/Rubric.persistence      21/ 23  18.3%/ 20.0%
tests/filesys/base/Rubric                      30/ 30  20.0%/ 20.0%
tests/userprog/Rubric.functionality           108/108  10.0%/ 10.0%
tests/userprog/Rubric.robustness               88/ 88   5.0%/  5.0%
tests/vm/Rubric.functionality                  55/ 55   8.0%/  8.0%
tests/vm/Rubric.robustness                     28/ 28   2.0%/  2.0%
--------------------------------------------- --- --- ------ ------
Total                                                  99.3%/110.0%

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

SUMMARY OF INDIVIDUAL TESTS

Functionality of extended file system (tests/filesys/extended/Rubric.functionality):
	- Test directory support.
	     1/ 1 tests/filesys/extended/dir-mkdir
	     3/ 3 tests/filesys/extended/dir-mk-tree

	     1/ 1 tests/filesys/extended/dir-rmdir
	     3/ 3 tests/filesys/extended/dir-rm-tree

	  ** 0/ 5 tests/filesys/extended/dir-vine

	- Test file growth.
	     1/ 1 tests/filesys/extended/grow-create
	     1/ 1 tests/filesys/extended/grow-seq-sm
	     3/ 3 tests/filesys/extended/grow-seq-lg
	     3/ 3 tests/filesys/extended/grow-sparse
	     3/ 3 tests/filesys/extended/grow-two-files
	     1/ 1 tests/filesys/extended/grow-tell
	     1/ 1 tests/filesys/extended/grow-file-size

	- Test directory growth.
	     1/ 1 tests/filesys/extended/grow-dir-lg
	     1/ 1 tests/filesys/extended/grow-root-sm
	     1/ 1 tests/filesys/extended/grow-root-lg

	- Test writing from multiple processes.
	     5/ 5 tests/filesys/extended/syn-rw

	- Section summary.
	     15/ 16 tests passed
	     29/ 34 points subtotal

Robustness of file system (tests/filesys/extended/Rubric.robustness):
	     1/ 1 tests/filesys/extended/dir-empty-name
	     1/ 1 tests/filesys/extended/dir-open
	     1/ 1 tests/filesys/extended/dir-over-file
	     1/ 1 tests/filesys/extended/dir-under-file

	  ** 0/ 3 tests/filesys/extended/dir-rm-cwd
	     2/ 2 tests/filesys/extended/dir-rm-parent
	     1/ 1 tests/filesys/extended/dir-rm-root

	- Section summary.
	      6/  7 tests passed
	      7/ 10 points subtotal

Persistence of file system (tests/filesys/extended/Rubric.persistence):
	     1/ 1 tests/filesys/extended/dir-empty-name-persistence
	     1/ 1 tests/filesys/extended/dir-mk-tree-persistence
	     1/ 1 tests/filesys/extended/dir-mkdir-persistence
	     1/ 1 tests/filesys/extended/dir-open-persistence
	     1/ 1 tests/filesys/extended/dir-over-file-persistence
	  ** 0/ 1 tests/filesys/extended/dir-rm-cwd-persistence
	     1/ 1 tests/filesys/extended/dir-rm-parent-persistence
	     1/ 1 tests/filesys/extended/dir-rm-root-persistence
	     1/ 1 tests/filesys/extended/dir-rm-tree-persistence
	     1/ 1 tests/filesys/extended/dir-rmdir-persistence
	     1/ 1 tests/filesys/extended/dir-under-file-persistence
	  ** 0/ 1 tests/filesys/extended/dir-vine-persistence
	     1/ 1 tests/filesys/extended/grow-create-persistence
	     1/ 1 tests/filesys/extended/grow-dir-lg-persistence
	     1/ 1 tests/filesys/extended/grow-file-size-persistence
	     1/ 1 tests/filesys/extended/grow-root-lg-persistence
	     1/ 1 tests/filesys/extended/grow-root-sm-persistence
	     1/ 1 tests/filesys/extended/grow-seq-lg-persistence
	     1/ 1 tests/filesys/extended/grow-seq-sm-persistence
	     1/ 1 tests/filesys/extended/grow-sparse-persistence
	     1/ 1 tests/filesys/extended/grow-tell-persistence
	     1/ 1 tests/filesys/extended/grow-two-files-persistence
	     1/ 1 tests/filesys/extended/syn-rw-persistence

	- Section summary.
	     21/ 23 tests passed
	     21/ 23 points subtotal

Functionality of base file system (tests/filesys/base/Rubric):
	- Test basic support for small files.
	     1/ 1 tests/filesys/base/sm-create
	     2/ 2 tests/filesys/base/sm-full
	     2/ 2 tests/filesys/base/sm-random
	     2/ 2 tests/filesys/base/sm-seq-block
	     3/ 3 tests/filesys/base/sm-seq-random

	- Test basic support for large files.
	     1/ 1 tests/filesys/base/lg-create
	     2/ 2 tests/filesys/base/lg-full
	     2/ 2 tests/filesys/base/lg-random
	     2/ 2 tests/filesys/base/lg-seq-block
	     3/ 3 tests/filesys/base/lg-seq-random

	- Test synchronized multiprogram access to files.
	     4/ 4 tests/filesys/base/syn-read
	     4/ 4 tests/filesys/base/syn-write
	     2/ 2 tests/filesys/base/syn-remove

	- Section summary.
	     13/ 13 tests passed
	     30/ 30 points subtotal

Functionality of system calls (tests/userprog/Rubric.functionality):
	- Test argument passing on Pintos command line.
	     3/ 3 tests/userprog/args-none
	     3/ 3 tests/userprog/args-single
	     3/ 3 tests/userprog/args-multiple
	     3/ 3 tests/userprog/args-many
	     3/ 3 tests/userprog/args-dbl-space

	- Test "create" system call.
	     3/ 3 tests/userprog/create-empty
	     3/ 3 tests/userprog/create-long
	     3/ 3 tests/userprog/create-normal
	     3/ 3 tests/userprog/create-exists

	- Test "open" system call.
	     3/ 3 tests/userprog/open-missing
	     3/ 3 tests/userprog/open-normal
	     3/ 3 tests/userprog/open-twice

	- Test "read" system call.
	     3/ 3 tests/userprog/read-normal
	     3/ 3 tests/userprog/read-zero

	- Test "write" system call.
	     3/ 3 tests/userprog/write-normal
	     3/ 3 tests/userprog/write-zero

	- Test "close" system call.
	     3/ 3 tests/userprog/close-normal

	- Test "exec" system call.
	     5/ 5 tests/userprog/exec-once
	     5/ 5 tests/userprog/exec-multiple
	     5/ 5 tests/userprog/exec-arg

	- Test "wait" system call.
	     5/ 5 tests/userprog/wait-simple
	     5/ 5 tests/userprog/wait-twice

	- Test "exit" system call.
	     5/ 5 tests/userprog/exit

	- Test "halt" system call.
	     3/ 3 tests/userprog/halt

	- Test recursive execution of user programs.
	    15/15 tests/userprog/multi-recurse

	- Test read-only executable feature.
	     3/ 3 tests/userprog/rox-simple
	     3/ 3 tests/userprog/rox-child
	     3/ 3 tests/userprog/rox-multichild

	- Section summary.
	     28/ 28 tests passed
	    108/108 points subtotal

Robustness of system calls (tests/userprog/Rubric.robustness):
	- Test robustness of file descriptor handling.
	     2/ 2 tests/userprog/close-stdin
	     2/ 2 tests/userprog/close-stdout
	     2/ 2 tests/userprog/close-bad-fd
	     2/ 2 tests/userprog/close-twice
	     2/ 2 tests/userprog/read-bad-fd
	     2/ 2 tests/userprog/read-stdout
	     2/ 2 tests/userprog/write-bad-fd
	     2/ 2 tests/userprog/write-stdin
	     2/ 2 tests/userprog/multi-child-fd

	- Test robustness of pointer handling.
	     3/ 3 tests/userprog/create-bad-ptr
	     3/ 3 tests/userprog/exec-bad-ptr
	     3/ 3 tests/userprog/open-bad-ptr
	     3/ 3 tests/userprog/read-bad-ptr
	     3/ 3 tests/userprog/write-bad-ptr

	- Test robustness of buffer copying across page boundaries.
	     3/ 3 tests/userprog/create-bound
	     3/ 3 tests/userprog/open-boundary
	     3/ 3 tests/userprog/read-boundary
	     3/ 3 tests/userprog/write-boundary

	- Test handling of null pointer and empty strings.
	     2/ 2 tests/userprog/create-null
	     2/ 2 tests/userprog/open-null
	     2/ 2 tests/userprog/open-empty

	- Test robustness of system call implementation.
	     3/ 3 tests/userprog/sc-bad-arg
	     3/ 3 tests/userprog/sc-bad-sp
	     5/ 5 tests/userprog/sc-boundary
	     5/ 5 tests/userprog/sc-boundary-2

	- Test robustness of "exec" and "wait" system calls.
	     5/ 5 tests/userprog/exec-missing
	     5/ 5 tests/userprog/wait-bad-pid
	     5/ 5 tests/userprog/wait-killed

	- Test robustness of exception handling.
	     1/ 1 tests/userprog/bad-read
	     1/ 1 tests/userprog/bad-write
	     1/ 1 tests/userprog/bad-jump
	     1/ 1 tests/userprog/bad-read2
	     1/ 1 tests/userprog/bad-write2
	     1/ 1 tests/userprog/bad-jump2

	- Section summary.
	     34/ 34 tests passed
	     88/ 88 points subtotal

Functionality of virtual memory subsystem (tests/vm/Rubric.functionality):
	- Test stack growth.
	     3/ 3 tests/vm/pt-grow-stack
	     3/ 3 tests/vm/pt-grow-stk-sc
	     3/ 3 tests/vm/pt-big-stk-obj
	     3/ 3 tests/vm/pt-grow-pusha

	- Test paging behavior.
	     3/ 3 tests/vm/page-linear
	     3/ 3 tests/vm/page-parallel
	     3/ 3 tests/vm/page-shuffle
	     4/ 4 tests/vm/page-merge-seq
	     4/ 4 tests/vm/page-merge-par
	     4/ 4 tests/vm/page-merge-mm
	     4/ 4 tests/vm/page-merge-stk

	- Test "mmap" system call.
	     2/ 2 tests/vm/mmap-read
	     2/ 2 tests/vm/mmap-write
	     2/ 2 tests/vm/mmap-shuffle

	     2/ 2 tests/vm/mmap-twice

	     2/ 2 tests/vm/mmap-unmap
	     1/ 1 tests/vm/mmap-exit

	     3/ 3 tests/vm/mmap-clean

	     2/ 2 tests/vm/mmap-close
	     2/ 2 tests/vm/mmap-remove

	- Section summary.
	     20/ 20 tests passed
	     55/ 55 points subtotal

Robustness of virtual memory subsystem (tests/vm/Rubric.robustness):
	- Test robustness of page table support.
	     2/ 2 tests/vm/pt-bad-addr
	     3/ 3 tests/vm/pt-bad-read
	     2/ 2 tests/vm/pt-write-code
	     3/ 3 tests/vm/pt-write-code2
	     4/ 4 tests/vm/pt-grow-bad

	- Test robustness of "mmap" system call.
	     1/ 1 tests/vm/mmap-bad-fd
	     1/ 1 tests/vm/mmap-inherit
	     1/ 1 tests/vm/mmap-null
	     1/ 1 tests/vm/mmap-zero

	     2/ 2 tests/vm/mmap-misalign

	     2/ 2 tests/vm/mmap-over-code
	     2/ 2 tests/vm/mmap-over-data
	     2/ 2 tests/vm/mmap-over-stk
	     2/ 2 tests/vm/mmap-overlap

	- Section summary.
	     14/ 14 tests passed
	     28/ 28 points subtotal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

DETAILS OF tests/filesys/extended/dir-vine FAILURE:

Test output failed to match any acceptable form.

Acceptable output:
  (dir-vine) begin
  (dir-vine) creating many levels of files and directories...
  (dir-vine) removing all but top 10 levels of files and directories...
  (dir-vine) end
Differences in `diff -u' format:
  (dir-vine) begin
  (dir-vine) creating many levels of files and directories...
- (dir-vine) removing all but top 10 levels of files and directories...
- (dir-vine) end

(Process exit codes are excluded for matching purposes.)

OUTPUT FROM tests/filesys/extended/dir-vine:

Copying tests/filesys/extended/dir-vine to scratch partition...
Copying tests/filesys/extended/tar to scratch partition...
qemu -hda /tmp/S_2Ts6gA02.dsk -hdb tmp.dsk -m 4 -net none -nographic -monitor null
PiLo hda1
Loading..............
Kernel command line: -q -f extract run dir-vine
Pintos booting with 4,088 kB RAM...
382 pages available in kernel pool.
380 pages available in user pool.
Calibrating timer...  261,734,400 loops/s.
hda: 9,072 sectors (4 MB), model "QM00001", serial "QEMU HARDDISK"
hda1: 229 sectors (114 kB), Pintos OS kernel (20)
hda2: 245 sectors (122 kB), Pintos scratch (22)
hda3: 8,192 sectors (4 MB), Pintos swap (23)
hdb: 5,040 sectors (2 MB), model "QM00002", serial "QEMU HARDDISK"
hdb1: 4,096 sectors (2 MB), Pintos file system (21)
filesys: using hdb1
scratch: using hda2
swap: using hda3
Formatting file system...done.
Boot complete.
Extracting ustar archive from scratch device into file system...
Putting 'dir-vine' into the file system...
Putting 'tar' into the file system...
Erasing ustar archive...
Executing 'dir-vine':
(dir-vine) begin
(dir-vine) creating many levels of files and directories...
dir-vine: exit(-1)
Execution of 'dir-vine' complete.
Timer: 134 ticks
Thread: 65 idle ticks, 63 kernel ticks, 6 user ticks
hdb1 (filesys): 572 reads, 572 writes
hda2 (scratch): 244 reads, 2 writes
hda3 (swap): 0 reads, 0 writes
Console: 1127 characters output
Keyboard: 0 keys pressed
Exception: 6 page faults
Powering off...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

DETAILS OF tests/filesys/extended/dir-rm-cwd FAILURE:

run: try to remove "a" (must fail: still open): FAILED

OUTPUT FROM tests/filesys/extended/dir-rm-cwd:

Copying tests/filesys/extended/dir-rm-cwd to scratch partition...
Copying tests/filesys/extended/tar to scratch partition...
qemu -hda /tmp/EcLhQT32BK.dsk -hdb tmp.dsk -m 4 -net none -nographic -monitor null
PiLo hda1
Loading..............
Kernel command line: -q -f extract run dir-rm-cwd
Pintos booting with 4,088 kB RAM...
382 pages available in kernel pool.
380 pages available in user pool.
Calibrating timer...  314,163,200 loops/s.
hda: 9,072 sectors (4 MB), model "QM00001", serial "QEMU HARDDISK"
hda1: 229 sectors (114 kB), Pintos OS kernel (20)
hda2: 245 sectors (122 kB), Pintos scratch (22)
hda3: 8,192 sectors (4 MB), Pintos swap (23)
hdb: 5,040 sectors (2 MB), model "QM00002", serial "QEMU HARDDISK"
hdb1: 4,096 sectors (2 MB), Pintos file system (21)
filesys: using hdb1
scratch: using hda2
swap: using hda3
Formatting file system...done.
Boot complete.
Extracting ustar archive from scratch device into file system...
Putting 'dir-rm-cwd' into the file system...
Putting 'tar' into the file system...
Erasing ustar archive...
Executing 'dir-rm-cwd':
(dir-rm-cwd) begin
(dir-rm-cwd) open "/"
(dir-rm-cwd) mkdir "a"
(dir-rm-cwd) open "/a"
(dir-rm-cwd) verify "/a" is empty
(dir-rm-cwd) "/" and "/a" must have different inumbers
(dir-rm-cwd) chdir "a"
(dir-rm-cwd) try to remove "/a"
(dir-rm-cwd) remove failed
(dir-rm-cwd) try to remove "../a" (must fail)
(dir-rm-cwd) try to remove ".././a" (must fail)
(dir-rm-cwd) try to remove "/./a" (must fail)
(dir-rm-cwd) open "/a"
(dir-rm-cwd) open "."
(dir-rm-cwd) "/a" and "." must have same inumber
(dir-rm-cwd) "/" and "/a" must have different inumbers
(dir-rm-cwd) chdir "/a"
(dir-rm-cwd) open "."
(dir-rm-cwd) "." must have same inumber as before
(dir-rm-cwd) chdir "/"
(dir-rm-cwd) try to remove "a" (must fail: still open)
(dir-rm-cwd) try to remove "a" (must fail: still open): FAILED
dir-rm-cwd: exit(1)
Execution of 'dir-rm-cwd' complete.
Timer: 136 ticks
Thread: 59 idle ticks, 71 kernel ticks, 6 user ticks
hdb1 (filesys): 562 reads, 562 writes
hda2 (scratch): 244 reads, 2 writes
hda3 (swap): 0 reads, 0 writes
Console: 1843 characters output
Keyboard: 0 keys pressed
Exception: 5 page faults
Powering off...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

DETAILS OF tests/filesys/extended/dir-rm-cwd-persistence FAILURE:

Prerequisite test tests/filesys/extended/dir-rm-cwd failed.

OUTPUT FROM tests/filesys/extended/dir-rm-cwd-persistence:

qemu -hda /tmp/RYnte4hJ0z.dsk -hdb tmp.dsk -m 4 -net none -nographic -monitor null
PiLo hda1
Loading..............
Kernel command line: -q run 'tar fs.tar /' append fs.tar
Pintos booting with 4,088 kB RAM...
382 pages available in kernel pool.
380 pages available in user pool.
Calibrating timer...  314,163,200 loops/s.
hda: 11,088 sectors (5 MB), model "QM00001", serial "QEMU HARDDISK"
hda1: 229 sectors (114 kB), Pintos OS kernel (20)
hda2: 2,048 sectors (1 MB), Pintos scratch (22)
hda3: 8,192 sectors (4 MB), Pintos swap (23)
hdb: 5,040 sectors (2 MB), model "QM00002", serial "QEMU HARDDISK"
hdb1: 4,096 sectors (2 MB), Pintos file system (21)
filesys: using hdb1
scratch: using hda2
swap: using hda3
Boot complete.
Executing 'tar fs.tar /':
tar: exit(0)
Execution of 'tar fs.tar /' complete.
Appending 'fs.tar' to ustar archive on scratch device...
Timer: 313 ticks
Thread: 73 idle ticks, 37 kernel ticks, 203 user ticks
hdb1 (filesys): 799 reads, 569 writes
hda2 (scratch): 0 reads, 249 writes
hda3 (swap): 0 reads, 0 writes
Console: 919 characters output
Keyboard: 0 keys pressed
Exception: 5 page faults
Powering off...
Copying tests/filesys/extended/dir-rm-cwd.tar out of /tmp/RYnte4hJ0z.dsk...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

DETAILS OF tests/filesys/extended/dir-vine-persistence FAILURE:

Prerequisite test tests/filesys/extended/dir-vine failed.

OUTPUT FROM tests/filesys/extended/dir-vine-persistence:

qemu -hda /tmp/rjIZp2Q3qr.dsk -hdb tmp.dsk -m 4 -net none -nographic -monitor null
PiLo hda1
Loading..............
Kernel command line: -q run 'tar fs.tar /' append fs.tar
Pintos booting with 4,088 kB RAM...
382 pages available in kernel pool.
380 pages available in user pool.
Calibrating timer...  261,734,400 loops/s.
hda: 11,088 sectors (5 MB), model "QM00001", serial "QEMU HARDDISK"
hda1: 229 sectors (114 kB), Pintos OS kernel (20)
hda2: 2,048 sectors (1 MB), Pintos scratch (22)
hda3: 8,192 sectors (4 MB), Pintos swap (23)
hdb: 5,040 sectors (2 MB), model "QM00002", serial "QEMU HARDDISK"
hdb1: 4,096 sectors (2 MB), Pintos file system (21)
filesys: using hdb1
scratch: using hda2
swap: using hda3
Boot complete.
Executing 'tar fs.tar /':
tar: exit(0)
Execution of 'tar fs.tar /' complete.
Appending 'fs.tar' to ustar archive on scratch device...
Timer: 315 ticks
Thread: 75 idle ticks, 33 kernel ticks, 207 user ticks
hdb1 (filesys): 819 reads, 593 writes
hda2 (scratch): 0 reads, 253 writes
hda3 (swap): 0 reads, 0 writes
Console: 919 characters output
Keyboard: 0 keys pressed
Exception: 5 page faults
Powering off...
Copying tests/filesys/extended/dir-vine.tar out of /tmp/rjIZp2Q3qr.dsk...
vagrant@vagrant-ubuntu-trusty-32:/vagrant/TeamE/Project5/src/filesys/build